name: CI

on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Package CloudFormation Stack
        run: aws cloudformation package --template-file template.yaml --s3-bucket aws-etl-lambda-code --output-template-file template.packaged.yaml
      - name: Deploy CloudFormation Stack
        run: aws cloudformation deploy --template-file template.packaged.yaml --stack-name ETL --capabilities CAPABILITY_IAM --parameter-overrides DBUsername=${{ secrets.DBUsername }} DBPassword=${{ secrets.DBPassword }}
